services:
  - type: web
    name: intellisearch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PRODUCTION
        value: true
      - key: PORT
        value: 10000
      - key: TOGETHER_AI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"  # We'll update this after frontend deployment 